version: '3.4'

services:
  webapplicationentrypoint:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8877:80"
    restart: always
    depends_on: 
      - rabbitmq
      - grafana
      - sql

  rabbitmq:
    container_name: RabbitMQ
    hostname: rabbitmq
    build: 
      context: ./rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672" #management
      - "15692:15692" #prometheus
      - "5672:5672"   #amqp
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:15672 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5         
    networks:
      - walkthrough-net
#    environment:
#      RABBITMQ_DEFAULT_USER: WalkthroughUser
#      RABBITMQ_DEFAULT_PASS: WalkthroughPassword
#      RABBITMQ_DEFAULT_VHOST: Walkthrough


  grafana:
    image: grafana/grafana:8.0.5-ubuntu
    environment: {
      "TZ": "America/Sao_Paulo"
    }
    ports:
      - "3000:3000"    
    volumes:
      - ./grafana/data/:/var/lib/grafana
    networks:
      - walkthrough-net

  sql:
      image: luizcarlosfaria/mssql-server-linux:2019-latest
      container_name: SQLServer
      hostname: mssql
      environment: {
        "ACCEPT_EULA" : "Y",
        "SA_PASSWORD" : "8k3W2C2BVzAW9p",
        "MSSQL_DATABASE" : "Walkthrough",
        "MSSQL_DATABASE_COLLATE" : "SQL_Latin1_General_CP1_CI_AI",
        "MSSQL_USER" : "WalkthroughUser",
        "MSSQL_PASSWORD" : "WalkthroughPass",
        "TZ": "America/Sao_Paulo"
      }
      ports: 
        - 1433:1433      
      networks:
      - walkthrough-net
      volumes:
        - sql_data:/var/opt/mssql/data
        - sql_log:/var/opt/mssql/log
        - sql_files:/var/opt/mssql/file_tables
        - ./sql/:/docker-entrypoint-initdb.d/
volumes:
  rabbitmq_data:
  sql_data:
  sql_log:
  sql_files:
